PSR-209 Added dispose of land or property page

diff --git a/.g8/scripts/updateNavigator b/.g8/scripts/updateNavigator
--- a/.g8/scripts/updateNavigator
+++ b/.g8/scripts/updateNavigator
@@ -1,17 +1,32 @@
 #!/bin/bash
 
-# use awk / sed to insert route to supplied navigator file and update navigator spec
+# uses sed to insert route to supplied navigator file and update navigator spec
 
 set -e
 
 [ -z "$1" ] && echo "missing first param PAGE" && exit 1
-[ -z "$2" ] && echo "missing second param NAVFILE" && exit 1
-[ -z "$3" ] && echo "missing third param SPECFILE" && exit 1
+[ -z "$2" ] && echo "missing first param DIR" && exit 1
 
 PAGE=$1
-NAVFILE=$2
-SPECFILE=$3
-INDEX=$4
+DIR=$2
+INDEX=$3
+
+case $DIR in
+  landorproperty)
+    NAV_FILE="../app/navigation/nonsipp/LandOrPropertyNavigator.scala"
+    NAV_SPEC="../test/navigation/nonsipp/LandOrPropertyNavigatorSpec.scala"
+    ;;
+  landorpropertydisposal)
+    NAV_FILE="../app/navigation/nonsipp/LandOrPropertyDisposalNavigator.scala"
+    NAV_SPEC="../test/navigation/nonsipp/LandOrPropertyDisposalNavigatorSpec.scala"
+    ;;
+  *)
+    NAV_FILE=
+    NAV_SPEC=
+    ;;
+esac
+
+[ -z "$NAV_FILE" ] && echo "unknown directory $DIR" && exit 1
 
 tmpfile=$(mktemp)
 echo "$tmpfile"
@@ -19,12 +34,12 @@ echo "$tmpfile"
 echo "updating navigator"
 
 if [ -z "$INDEX" ]; then
-  awk "/[ ]*case _ => controllers.routes.UnauthorisedController.onPageLoad\(\)$/{ print \"    case $PAGE(srn) => controllers.routes.UnauthorisedController.onPageLoad()\"; print \"\"}1" RS="\n" FS="\n" "$NAVFILE" > "$tmpfile"
+  sed "s/\( *override def normalRoutes.*\)/& \n\n case $PAGE(srn) => controllers.routes.UnauthorisedController.onPageLoad()/" "$NAV_FILE" > "$tmpfile"
 else
-  awk "/[ ]*case _ => controllers.routes.UnauthorisedController.onPageLoad\(\)$/{ print \"    case $PAGE(srn, index) => controllers.routes.UnauthorisedController.onPageLoad()\"; print \"\"}1" RS="\n" FS="\n" "$NAVFILE" > "$tmpfile"
+  sed "s/\( *override def normalRoutes.*\)/& \n\n case $PAGE(srn, index) => controllers.routes.UnauthorisedController.onPageLoad()/" "$NAV_FILE" > "$tmpfile"
 fi
 cat "$tmpfile"
-cp "$tmpfile" "$NAVFILE"
+cp "$tmpfile" "$NAV_FILE"
 rm "$tmpfile"
 
 tmpfile=$(mktemp)
@@ -45,8 +60,8 @@ sed "\$s/\(}\)/\n  \"$PAGE\" - {\n"\
 "      )\n"\
 "      .withName(\"go from $PAGE to ??? page\")\n"\
 "    )\n"\
-"  }\n\1/" "$SPECFILE" > "$tmpfile"
+"  }\n\1/" "$NAV_SPEC" > "$tmpfile"
 cat "$tmpfile"
-cp "$tmpfile" "$SPECFILE"
+cp "$tmpfile" "$NAV_SPEC"
 rm "$tmpfile"
 fi
